# Clones and builds static frameworks of WebP for Apple's platforms, and releases them on GitHub.

name: Release New WebP Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'WebP Version Tag'     
        required: true
        default: 'v1.1.0'

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Check out the repo with our CI bot's credentials
      - name: Check out WebP-Cococa
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN }}

      # Execute fastlane
      - name: Run Fastlane
        run: bundle install && bundle exec fastlane package tag:${{ github.event.inputs.version }}
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}

